### PR TITLE
improved property card UI 

### PR DESCRIPTION
**Pull request by AbhinavReddy-Dev**
#76

### CODE REVIEW

**Comment by AbhinavReddy-Dev** [comment]
This pull has improved UI for property card and other minor changes to UI overall.

Can you please label this?

**Comment by AbhinavReddy-Dev** [comment]
@lazyfuhrer Hey, I don't know if you got an email regarding this pull request, if not please check the pull request.

**Comment by lazyfuhrer** [comment]
Done

**Comment by AbhinavReddy-Dev** [comment]
Thank you, can you also add the label to the issue and close it?

**Pull request merged**
