### PR TITLE
added Contact Us. Footer looks much better now.

### PR DESCRIPTION
**Pull request by goodchai0**
Earlier-

Now-

### CODE REVIEW

**Comment by goodchai0** [comment]
Do response as I did my best to updating the code.

**Comment by lazyfuhrer** [comment]
please check with the code. vercel couldn't deploy.

**Comment by goodchai0** [comment]
Can you help me please, I can find any error in my code all I added is css.

**Comment by goodchai0** [comment]
Made the changes. Please merge it. Everything resolved.

**Pull request merged**
